#!/usr/bin/env bash
#
# Maintains a list of Courses that are currently active on the system. Allowing
# for the user to easily access information and file path to the specified
# Course
#
# Written by: Cooper Wallace

###############################################################################
# This Script will be responsible for managing and maintaining the path of each
# Course that has been added to its database. It will allow the user to browse the
# Courses that currently exist in the database, browse the Lectures in a Course,
# and finally give the path to a Lecture in a specific Course.
#
# This script should have the following capabilities:
#
# 1. Ability to Add Courses to the Database
# 	- Active for adding new lecture
# 	- Directory for searching
# 2. Browse the Courses in the Database
# 	- Obtain the path of a specific course
# 3. Browse Lectures that belong to a specific course
# 4. Obtain the Path to either
# 	- A Specified Lecture
# 	- The Path to a new Lecture file. Lecture(X+1).md
###############################################################################

# Display the Usage Documentation message
usage() {
	echo -n "Usage: $0 [-aglh] [-c course]

Help maintain and manage Notes for specified courses on the Users system.

 Options:
  -h	Display usage message
  -a	Add a Course
  -l	List Courses
  -g	Get Course Directory
"
}

################################################################################
# Course management Database functions
# 	Functions dedicated to parsing and interacting with the Course Database

# Set the Database file for the Program, or create one if it doesnt exist.
#	The Database shall contain all information regarding courses
# Globals:
#	DB_PATH	- READONLY Contains the path to the config file
#	DB_FILE	- READONLY Contains the contents of the Config file
init_db() {
	readonly DB_PATH="test.json"

	if [[ -e "$DB_PATH" ]]; then
		readonly DB_FILE=$(< "$DB_PATH")
	else
		echo "Generating new config"
		DB_FILE=""
	fi

	# Setup basic JSON for empty file
	if [[ $DB_FILE == "" ]]; then
		echo "Config empty, Generating new"
		echo "{\"Courses\":{}}" | jq > $DB_PATH
		readonly DB_FILE=$(< "$DB_PATH")
	fi
}

# Determines if a Course with the specified name currently exists in the
# database
# Arguments:
#		Course name
# Returns:
#		0 if the Course exists, otherwise non-zero
course_exists () {
	local COURSE_NAME="$1"
	local QUERY=$(printf "jq -e '.[] | select( .| has(\"%s\"))'" $COURSE_NAME)

	( eval $QUERY <<< $DB_FILE > /dev/null )
	return $?
}

# Add Course to Data Structure
# Arguments:
#	Course Name
#	Directry
add_course_to_db() {
	local COURSE_NAME="$1"
	local DIRECTORY_PATH="$2"

	# Database query to Add Course
	QUERY=$(printf "jq '.Courses += {\"%s\": {\"dir\": \"%s\"}}' test.json" \
		"$COURSE_NAME" \
		"$DIRECTORY_PATH")

 	DB=$(eval $QUERY)

	cp "$DB_PATH" "${DB_PATH}.bak"
 	echo $DB > "$DB_PATH"
}

# Return the Directory that corresponds to the specified Course, if it exists
#
# GLOBAL:
#	DIRECTORY - Path to the specified course
# Arguments:
#	Course - Name of Course to search
# Returns:
#	0 on success, otherwise non-zero
get_course_directory () {
	local COURSE
	COURSE="$1"

	# Determine if a course was specified
	if [[ -z $COURSE ]] || [[ "$COURSE" == "" ]]; then
		echo "No Course specified"
		exit 1
	fi

	DIRECTORY=$(jq -r --arg v "$COURSE" '.Courses[$v].dir' <<< $DB_FILE)

	if [[ $DIRECTORY == "null" ]]; then
		return 1
	fi

}

# Display the Courses that currently exist in the Database
get_courses () {
	readarray -t CourseNames < <(echo $DB_FILE | jq -r ".Courses | keys[]")

	if (( ${#CourseNames[@]} == 0 )); then
		echo "No Courses currently exist in the database."
		echo "You may add one by using -a option"
		exit
	fi

	printf "%s\n" "${CourseNames[@]}"
}

################################################################################

# Handler for Interactively adding a new Course into the Database
handle_add_course() {
	local COURSE_NAME=""
	local DIRECTORY_PATH=""

	while [[ $COURSE_NAME == "" ]]; do
		printf "Course Name: "
		read COURSE_NAME
	done

	course_exists "$COURSE_NAME"

	if [[ $? == 0 ]]; then
		echo "A Course by that name already exists."
		exit 1
	fi

	while [[ $DIRECTORY_PATH == "" ]]; do
		printf "Path: "
		read DIRECTORY_PATH
	done

	if [ ! -d "$DIRECTORY_PATH" ]; then
		printf "Path does not exist.\n%s\n" "$DIRECTORY_PATH"
		exit
	fi

	printf "Confirmation\nCourse: %s\nDirectory: %s\nCreate Course? (Yy)\n" \
		"$COURSE_NAME" \
		"$DIRECTORY_PATH"
	read resp

	if [[ ! "${resp,,}" == "y" ]]; then
		printf "Aborting"
		exit
	fi

	add_course_to_db "$COURSE_NAME" "$DIRECTORY_PATH"
}

# Outputs a list of Lectures that belongs to the specified Course if it exists
# Arguments:
#	Course name
get_course_lectures () {
	local COURSE
	COURSE="$1"

	get_course_directory "$COURSE"

	if [[ $? == 1 ]]; then
		echo "Course doesn't exist in Database."
		exit
	fi

	# List Lectures contained in the Course
	ls "$DIRECTORY" | grep "Lecture" | sort --version-sort
}

################################################################################

# Initialize Configuration file containing Database
init_db

while getopts ":lahg:c:e:" o; do
	case "${o}" in
		l)
			get_courses
			;;
		h)
			usage
			;;
		a)
			handle_add_course
			;;
		e)
			courseName=${OPTARG}
			course_exists $courseName
			echo $?
			;;
		g)
			courseName=${OPTARG}
			get_course_directory "$courseName"
			;;
		c)
			courseName=${OPTARG}
			get_course_lectures "$courseName"
			;;
		*)
			usage
			;;
	esac
done

shift $((OPTIND-1))

