#!/usr/bin/env bash
#
# Auto increment and save figures
# Obtain the number of the most recent lecture file, obtain the last number of
# the last created figure for that lecture, and accept a new screenshot at
# l<d>-fig<d+1>.png

if [[ ! -d "$(pwd)/figures" ]]; then
	echo "Cannot find subdirectory 'figures'"
	exit -1
fi

# Get the last lecture, and obtain only the lecture number
lastLecture=$(ls Lecture* | sort -V | tail -n1 | sed -e 's/[^0-9]//g')

# Get the Number of the last figure, otherwise 1
lastFig=$(ls figures/l$lastLecture* 2>/dev/null \
        | sort -V \
        | grep -o 'fig[0-9]\{1,\}' \
        | tail -n1 \
        | tr -d '[[:alpha:]]')
newFig=$(expr $lastFig + 1)

# Take the screenshot and save to path specified
scrotStr="$(pwd)/figures/l$lastLecture-fig$newFig.jpg"
scrot -s "$scrotStr"

if [[ $? == 0 ]]; then
	echo "l$lastLecture-fig$newFig.jpg"
fi
